import { pgTable, text, timestamp, uuid, pgEnum, jsonb, AnyPgColumn, boolean } from 'drizzle-orm/pg-core';

// 1. Roles Definition
export const roleEnum = pgEnum('role', ['GLOBAL_ADMIN', 'PSICOLOGO', 'ALUNO', 'FAMILIAR']);

// 2. Users Table (Unified for Multitenancy)
export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(),
  role: roleEnum('role').notNull().default('ALUNO'),
  name: text('name').notNull(),
  
  // E-mail for user verification (Mandatory)
  email: text('email').notNull().unique(),
  
  cpf: text('cpf').unique(),
  crp: text('crp'),
  clinicName: text('clinic_name'),
  
  // Password Hash or PIN Code Hash
  passwordHash: text('password_hash'),
  
  // MULTITENANCY LINK: If ALUNO or FAMILIAR, this points to their PSICOLOGO's User ID
  psicologoId: uuid('psicologo_id').references((): AnyPgColumn => users.id),
  
  // Deprecated Optional: For FAMILIAR, link them to the specific ALUNO
  alunoId: uuid('aluno_id').references((): AnyPgColumn => users.id),
  
  // For FAMILIAR, unique phone number (so we can reuse them across multiple children)
  phone: text('phone').unique(),
  
  // For ALUNO, specific child details
  age: text('age'),
  gender: text('gender'),
  hasTdah: boolean('has_tdah').default(false),
  guardianId: uuid('guardian_id').references((): AnyPgColumn => users.id),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

// 3. Games Table (Catalog of Minigames/Mechanics)
export const games = pgTable('games', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  description: text('description').notNull(),
  clinicalTarget: text('clinical_target'), // e.g., 'WISC-V', 'CBCL'
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// 4. Game Sessions (Logs the activity of ALUNO playing a Game)
export const gameSessions = pgTable('game_sessions', {
  id: uuid('id').defaultRandom().primaryKey(),
  alunoId: uuid('aluno_id').references(() => users.id).notNull(),
  gameId: uuid('game_id').references(() => games.id).notNull(),
  
  startedAt: timestamp('started_at').defaultNow().notNull(),
  finishedAt: timestamp('finished_at'),
  
  // Raw behavioral data extracted during play (prosody, response time, clicks)
  behaviorData: jsonb('behavior_data'),
  
  // Analytical insights generated by the AI (flagged patterns)
  flaggedPatterns: jsonb('flagged_patterns'),
});

// 5. Anamneses Table (Clinical Anamnese per Patient & Psychologist)
export const anamneses = pgTable('anamneses', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => users.id).notNull(),
  psicologoId: uuid('psicologo_id').references(() => users.id).notNull(),
  
  status: text('status').notNull().default('draft'), // 'draft' | 'completed'
  content: jsonb('content').notNull().default({}),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

// 6. Clinical Notes Table (Notepad observations per Patient & Psychologist)
export const clinicalNotes = pgTable('clinical_notes', {
  id: uuid('id').defaultRandom().primaryKey(),
  patientId: uuid('patient_id').references(() => users.id).notNull(),
  psicologoId: uuid('psicologo_id').references(() => users.id).notNull(),
  
  category: text('category').notNull().default('Sessão'), // 'Sessão' | 'Família' | 'Escola' | 'Outros'
  title: text('title').notNull(), // Content/observation text of the note
  color: text('color').default('#3B82F6'),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});

// 7. Appointments Table (Agenda sessions per Psychologist)
export const appointments = pgTable('appointments', {
  id: uuid('id').defaultRandom().primaryKey(),
  psicologoId: uuid('psicologo_id').references(() => users.id).notNull(),
  patientId: uuid('patient_id').references(() => users.id),
  
  date: text('date').notNull(), // 'YYYY-MM-DD'
  startTime: text('start_time').notNull(), // 'HH:mm'
  endTime: text('end_time').notNull(), // 'HH:mm'
  
  title: text('title').notNull(),
  name: text('name').notNull(), // Patient/client name
  type: text('type').notNull(), // e.g. 'Avaliação Cognitiva', 'Terapia Infantil'
  status: text('status').notNull().default('confirmado'), // 'confirmado' | 'aguardando' | 'cancelado'
  color: text('color').default('#10B981'),
  
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  deletedAt: timestamp('deleted_at'),
});



