import { pgTable, text, timestamp, uuid, pgEnum, jsonb, AnyPgColumn } from 'drizzle-orm/pg-core';

// 1. Roles Definition
export const roleEnum = pgEnum('role', ['GLOBAL_ADMIN', 'PSICOLOGO', 'ALUNO', 'FAMILIAR']);

// 2. Users Table (Unified for Multitenancy)
export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(),
  role: roleEnum('role').notNull().default('ALUNO'),
  name: text('name').notNull(),
  
  // E-mail is optional because an ALUNO might login using only a PIN Code
  email: text('email').unique(),
  
  cpf: text('cpf').unique(),
  crp: text('crp'),
  clinicName: text('clinic_name'),
  
  // Password Hash or PIN Code Hash
  passwordHash: text('password_hash'),
  
  // MULTITENANCY LINK: If ALUNO or FAMILIAR, this points to their PSICOLOGO's User ID
  psicologoId: uuid('psicologo_id').references((): AnyPgColumn => users.id),
  
  // Optional: For FAMILIAR, link them to the specific ALUNO
  alunoId: uuid('aluno_id').references((): AnyPgColumn => users.id),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// 3. Games Table (Catalog of Minigames/Mechanics)
export const games = pgTable('games', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  description: text('description').notNull(),
  clinicalTarget: text('clinical_target'), // e.g., 'WISC-V', 'CBCL'
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// 4. Game Sessions (Logs the activity of ALUNO playing a Game)
export const gameSessions = pgTable('game_sessions', {
  id: uuid('id').defaultRandom().primaryKey(),
  alunoId: uuid('aluno_id').references(() => users.id).notNull(),
  gameId: uuid('game_id').references(() => games.id).notNull(),
  
  startedAt: timestamp('started_at').defaultNow().notNull(),
  finishedAt: timestamp('finished_at'),
  
  // Raw behavioral data extracted during play (prosody, response time, clicks)
  behaviorData: jsonb('behavior_data'),
  
  // Analytical insights generated by the AI (flagged patterns)
  flaggedPatterns: jsonb('flagged_patterns'),
});
